### ISSUE TITLE
Deprecated selector in `atom-overtype-mode\styles\overtype-mode.atom-text-editor.less`

### ISSUE THREAD

**Issue by mateddy** [brunetton/atom-overtype-mode#16]
In `atom-overtype-mode\styles\overtype-mode.atom-text-editor.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor.overtype-cursor::shadow .cursors .cursor` => `atom-text-editor.overtype-cursor.editor .cursors .cursor`

* `atom-text-editor.overtype-cursor::shadow .cursors.blink-off .cursor` => `atom-text-editor.overtype-cursor.editor .cursors.blink-off .cursor`

* `atom-text-editor[mini]:not(.is-focused)::shadow .cursors .cursor` => `atom-text-editor[mini]:not(.is-focused).editor .cursors .cursor`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by brunetton** [comment]
Thank for the trick.
If someone make a PR, I'll merge it quickly.

**Comment by CheeseSucker** [comment]
Fixed in v0.3.3
