### ISSUE TITLE
Deploy the enhanced version as an Atom package.

### ISSUE THREAD

**Issue by cornelius-dol** [brunetton/atom-overtype-mode#24]
Can this enhanced version be deployed to atom, as an update to the current package?

**Comment by brunetton** [comment]
Hi, I'm not using Atom and so not maintaining this project anymore.
If anyone is interested in helping, I can add people to the project maintainers so people can commit. So if you want to update this package, you're welcome!

**Comment by cornelius-dol** [comment]
I'm willing to take it over, though this will be my first time doing do, and I have no idea what that looks like.

What editor did you switch to?

**Comment by cornelius-dol** [comment]
Also, can you transfer ownership to me, including the Atom package so I can publish updates without creating a new package name?

**Comment by cornelius-dol** [comment]
@Asc2011 : FYI.
