### ISSUE TITLE
No cursor change when activating overtype mode

### ISSUE THREAD

**Issue by notargets** [brunetton/atom-overtype-mode#5]
I [read] (https://atom.io/packages/atom-overtype-mode) that the cursor should change when I press Insert. However, it actually stays the same all the time. I am using Atom 0.176.0 under Manjaro Linux.

**Comment by splendido** [comment]
please update :-)
tnx!

**Comment by doncx** [comment]
Yes, please update!  I can't figure out this seemingly simple deprecation.

Many thanks for this important little package!

**Comment by notargets** [comment]
The problem still exist. Could you fix it, please?

**Comment by brunetton** [comment]
Try to If disable *shadow DOM* in Atom settings : 
https://github.com/atom/atom/issues/4962

https://gist.github.com/brunetton/a55c6e8735eeee68067b

Does it works ? It's a quick'n dirty fix for now.

I'm sure that the problem should be solved by @muchweb [pull request](https://github.com/brunetton/atom-overtype-mode/pull/3/commits)
Shame on me having forgot to merge that !

I need to find time for that. Sorry guys ! I'll buy you beers ;)

**Comment by muchweb** [comment]
>I'll buy you beers ;)

I'd rather have a coffee. Thanks, mate :smile_cat:

**Comment by notargets** [comment]
No problem. I appreciate your work.

> Try to If disable shadow DOM in Atom settings : 

It solves the issue for now. Thank you!

**Comment by brunetton** [comment]
Fixed by #3. Thanks again @muchweb
